### ISSUE TITLE
fails to build with clang

### ISSUE THREAD

**Issue by yurivict** [quamplex/redkite#31] opened 2019-08-05 23:20 UTC
clang8 on FreeBSD fails to build it:

```
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:65:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int width() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:67:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.x() - rectTopLeft.x());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkMain.cpp:26:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:75:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int height() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:77:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.y() - rectTopLeft.y());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
2 errors generated.
[2/50] /usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o -MF CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o.d -o CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkCairoGraphicsBackend.cpp
FAILED: CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o 
/usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o -MF CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o.d -o CMakeFiles/redkite.dir/src/RkCairoGraphicsBackend.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkCairoGraphicsBackend.cpp
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkCairoGraphicsBackend.cpp:24:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/RkCairoGraphicsBackend.h:31:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:65:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int width() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:67:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.x() - rectTopLeft.x());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkCairoGraphicsBackend.cpp:24:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/RkCairoGraphicsBackend.h:31:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:75:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int height() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:77:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.y() - rectTopLeft.y());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkCairoGraphicsBackend.cpp:24:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/RkCairoGraphicsBackend.h:61:13: warning: private field 'fontSize' is not used [-Wunused-private-field]
        int fontSize;
            ^
1 warning and 2 errors generated.
[3/50] /usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o -MF CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o.d -o CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidgetImpl.cpp
FAILED: CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o 
/usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o -MF CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o.d -o CMakeFiles/redkite.dir/src/RkWidgetImpl.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidgetImpl.cpp
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidgetImpl.cpp:24:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/RkWidgetImpl.h:27:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:65:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int width() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:67:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.x() - rectTopLeft.x());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidgetImpl.cpp:24:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/RkWidgetImpl.h:27:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:75:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int height() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:77:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.y() - rectTopLeft.y());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
2 errors generated.
[4/50] /usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkTimer.cpp.o -MF CMakeFiles/redkite.dir/src/RkTimer.cpp.o.d -o CMakeFiles/redkite.dir/src/RkTimer.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkTimer.cpp
[5/50] /usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkWidget.cpp.o -MF CMakeFiles/redkite.dir/src/RkWidget.cpp.o.d -o CMakeFiles/redkite.dir/src/RkWidget.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidget.cpp
FAILED: CMakeFiles/redkite.dir/src/RkWidget.cpp.o 
/usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkWidget.cpp.o -MF CMakeFiles/redkite.dir/src/RkWidget.cpp.o.d -o CMakeFiles/redkite.dir/src/RkWidget.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidget.cpp
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidget.cpp:25:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:65:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int width() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:67:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.x() - rectTopLeft.x());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkWidget.cpp:25:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:75:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int height() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:77:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.y() - rectTopLeft.y());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
2 errors generated.
[6/50] /usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o -MF CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o.d -o CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkEventQueueImpl.cpp
FAILED: CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o 
/usr/bin/c++   -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl -I/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/impl/platforms/xwin -Wall -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fvisibility=hidden -DRK_GRAPHICS_CAIRO_BACKEND -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -fPIC -std=gnu++14 -MD -MT CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o -MF CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o.d -o CMakeFiles/redkite.dir/src/RkEventQueueImpl.cpp.o -c /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkEventQueueImpl.cpp
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkEventQueueImpl.cpp:25:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:65:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int width() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:67:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.x() - rectTopLeft.x());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/src/RkEventQueueImpl.cpp:25:
In file included from /usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkWidget.h:30:
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:75:23: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
        constexpr int height() const
                      ^
/usr/ports/x11-toolkits/redkite/work/redkite-0.6/include/RkRect.h:77:24: note: non-constexpr function 'abs' cannot be used in a constant expression
                return std::abs(rectBottomRight.y() - rectTopLeft.y());
                       ^
/usr/include/stdlib.h:87:6: note: declared here
int      abs(int) __pure2;
         ^
```

**Comment by iurienistor** [comment] 2019-08-06 10:50
Hi! Thank you for reporting this issue. The problem is that I haven't targeted to support clang for now. clang should be compatible with GCC... but it seems not. Also I have never used clang, do not have experience with it.

**Comment by yurivict** [comment] 2019-08-06 15:03
Just install it with the package, and reproduce the problems. -)

**Comment by iurienistor** [comment] 2019-08-06 19:39
Yes, I understand, I need to get read of abs since is not constexpr. I have fixed this before in feat/windows which is in the development phase. I'll make now a hot fix for this.

**Comment by iurienistor** [comment] 2019-08-06 20:09
Ok, I have fixed it, tested it with clang 7 under Debian, I think this will work also on clang8. Tell me if now works. Clone from master branch. Anyway there is a need to remove some warnings, but later.  Thank you :)

**Closed** 2019-08-06 20:09 UTC
Labels: deploy, feature
